### ISSUE TITLE
ROIpoly stopped displaying in terminal running python 3.7 or virtual environment in Conda

### ISSUE THREAD

**Issue by IshTheCoder** [jdoepfert/roipoly.py#30]
Running example and getting no image displayed when clicking anymore.
<img width="645" alt="Screen Shot 2020-01-28 at 3 23 42 PM" src="https://user-images.githubusercontent.com/29733527/73314279-4e485900-41e2-11ea-81cd-6d1deb72f377.png">

**Comment by georgedeath** [comment]
Could you please provide some more information on this? If i do the following I cannot recreate your bug:
```shell
> git clone https://github.com/jdoepfert/roipoly.py
Cloning into 'roipoly.py'...
remote: Enumerating objects: 282, done.
Receiving objects:  97% (274/282)ed 0 (delta 0), pack-reused 282 eceiving objects:  96% (271/282)
Receiving objects: 100% (282/282), 99.15 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (141/141), done.

> cd roipoly.py
> python examples\basic_example.py
```

**Comment by hackerman084** [comment]
I am also having the same issue, even when I replicate your steps. I am running this in a python virtual environment as well. Even when I try to run it locally (not in any environment) it will not allow me to create line segments. I am not seeing any of the debug messages referring to when I left or right click within the window, leading me to believe that it is not registered mouse clicks. When I exit the application, this is all I see 
<img width="592" alt="Screen Shot 2020-03-05 at 12 37 48 PM" src="https://user-images.githubusercontent.com/36517450/76008730-21bce680-5ede-11ea-8d33-5da97aba449d.png">
I am running Python 3.8.1 on a Macbook

**Comment by jdoepfert** [comment]
@hackerman084 which matplotlib and numpy versions are you running?

**Comment by acunam** [comment]
same error here:

 File "C:/Users/macuna/OneDrive/Documents/LogVision/Roipoly2/basic_example.py", line 29, in <module>
    roi1.display_roi()
  File "C:\Users\macuna\AppData\Local\Continuum\anaconda3\envs\pythoncv\lib\site-packages\roipoly\roipoly.py", line 97, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
IndexError: list index out of range

Python 3.6, NumPy 1.18.4, Matplotlib 3.2.1

**Comment by shalgi** [comment]
@jdoepfert  @acunam @IshTheCoder  did you manage to solve this issue?
python 3.7.1 numpy 1.19.0 matplotlit 3.2.2 on windows using pycharm here

**Comment by juicetinliu** [comment]
Had the same issue and solved it by changing `event.dblclick is ...` to `event.dblclick == ...` on lines 132, 160, and 161 in `roipoly.py`.

**Comment by jdoepfert** [comment]
@juicetinliu that's interesting, thanks for the hint. Will try to check and potentially fix it in the next days

**Comment by jdoepfert** [comment]
should work now according to @juicetinliu with the most recent version (0.5.3)

**Comment by miguel-996** [comment]
Apologies for arriving late to the party. I am still getting the same error as mentioned above, it's not even letting me select the ROI, so the interactive aspect is not quite working. I tried fiddling with event.dblclick in roipoly.py but without success.
Python 3.9.6
matplotlib 3.5.3
numpy 1.23.2
